version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: inboxos-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: inboxos
      POSTGRES_PASSWORD: inboxos123
      POSTGRES_DB: inboxos
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
